import { StyleSheet } from 'react-native';

export const defaultStyles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 10,
  },
  closeIconStyle: {
    width: 12,
    height: 12,
    tintColor: 'black',
  },
  inputRowWrapper: {
    marginBottom: 20,
  },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: 10,
    borderColor: '#ccc',
  },
  input: {
    flex: 1,
    height: 50,
    paddingLeft: 10,
    paddingRight: 10,
    marginHorizontal: 5,
    overflow: 'scroll',
    paddingTop: 15,
  },
  uploadButton: {
    padding: 5,
  },
  message: {
    padding: 10,
    backgroundColor: '#f0f0f0',
    marginBottom: 5,
    borderRadius: 5,
  },
  previewImage: {
    width: 45,
    height: 45,
    position: 'relative',
    marginRight: 8,
  },
  imagePreviewContainer: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 6,
    overflow: 'hidden',
  },
  imageStyle: {
    width: '100%',
    height: '100%',
    borderRadius: 6,
  },
  previewCloseContainer: {
    position: 'absolute',
    top: -6,
    right: -6,
    backgroundColor: 'white',
    borderRadius: 9999,
    padding: 4,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.41,
  },
  fileTextStyle: {
    fontSize: 12,
    color: '#1f2937',
    maxWidth: 80,
  },
  previewContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
    backgroundColor: '#e0e0e0',
    padding: 5,
    borderRadius: 5,
    overflow: 'scroll',
  },
  filePreviewContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: '#f3f4f6',
    borderRadius: 6,
    paddingHorizontal: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  filePreview: {
    width: 100,
    height: 50,
    position: 'relative',
    marginRight: 8,
  },
  previewThumbnail: {
    width: 50,
    height: 50,
    marginRight: 10,
    borderRadius: 5,
  },
  removePreview: {
    fontSize: 18,
    marginLeft: 10,
    color: 'red',
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0,0,0,0.5)',
  },
  modalContent: {
    backgroundColor: 'white',
    padding: 20,
    borderTopLeftRadius: 12,
    borderTopRightRadius: 12,
  },
  modalOption: {
    padding: 10,
    fontSize: 16,
  },
  cancelOption: {
    color: 'red',
  },
  previewItem: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
    padding: 5,
    borderRadius: 5,
    marginRight: 10,
    position: 'relative',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: '#000',
    justifyContent: 'center',
    alignItems: 'center',
  },
  closeArea: {
    position: 'absolute',
    top: 40,
    right: 20,
    zIndex: 1,
  },
  fullImage: {
    width: '100%',
    height: '100%',
  },
  uploadIconStyle: {
    width: 24,
    height: 24,
    tintColor: 'black'
  },
});